jobs:
  main:
    image: docker.io/library/node:20
    requires: []
    steps:
      - step1: curl https://www.yahoo.co.jp
      # generate big log for test
      - biglog: for i in $(seq $((1024*1024))); do LC_ALL=C tr -dc 'a-zA-Z0-9' </dev/urandom | head -c $((1024*2)); echo; done
      - teardown-step3: sleep 5
