jobs:
  main:
    image: docker.io/library/node:20
    requires: [ virtual ]
    steps:
      - step1: echo test
      - step2: curl https://www.yahoo.co.jp
      - step3: dd if=/dev/urandom of=testfile bs=1024 count=1000; test 1 = 2
      - teardown-step4: sleep 300
