jobs:
  main:
    image: node:20
    environment:
      TERM: xterm
      USER_SHELL_BIN: bash
    requires: [ ~pr, ~commit ]
    steps:
      - test: echo test
  virtual:
    image: node:lts
    annotations:
      screwdriver.cd/virtualJob: true
    steps:
    - echo: echo ok
