jobs:
  main:
    image: docker.io/library/node:20
    environment:
      TERM: xterm
      USER_SHELL_BIN: bash
    requires: [ virtual ]
    steps:
      - test: echo test
      - curl: curl https://www.yahoo.co.jp
      - sleep: sleep 312
  virtual:
    image: node:lts
    requires: [ ~commit ]
    annotations:
      screwdriver.cd/virtualJob: true
    steps:
    - echo: echo ok
