jobs:
  main:
    image: docker.io/library/node:20
    requires: []
    steps:
      - step1: curl https://www.yahoo.co.jp
      - step2: for i in $(seq $((1024*100))); do LC_ALL=C tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 1024; echo; sleep 0.05; done
      - teardown-step3: sleep 5
